
color = [
    [0.0, 0.0, 0.0],
    [0.0, 0.0, 0.6666667],
    [0.6666667, 0.0, 0.0],
    [0.6666667, 0.0, 0.6666667],
    [0.0, 0.6666667, 0.0],
    [0.0, 0.6666667, 0.6666667],
    [0.6666667, 0.6666667, 0.0],
    [0.8666667, 0.8666667, 0.8666667],
    [0.4, 0.4, 0.4],
    [0.0, 0.0, 1.0],
    [1.0, 0.0, 0.0],
    [1.0, 0.0, 1.0],
    [0.0, 1.0, 0.0],
    [0.0, 1.0, 1.0],
    [1.0, 1.0, 0.0],
    [1.0, 1.0, 1.0]
]


[characters]
"~" = { color = 5, char = 0xcd, solid = true }
"|" = { color = 4, char = 0xdf, solid = true }
"^" = { color = 8, char = 0xce, solid = true }
"=" = { color = 6, char = 0xdd, solid = false }
"," = { color = 6, char = 0xcc, solid = false }
" " = { color = 1, char = 0x20, solid = false }
"T" = { color = 15, char = 0xcb, solid = false }
"O" = { color = 0, char = 0x20, solid = false }
"#" = { color = 8, char = 0x87, solid = true }
"." = { color = 8, char = 0xdc, solid = false }
"+" = { color = 6, char = 0xc9, solid = false }
"]" = { color = 6, char = 0x84, solid = true }
"0" = { color = 15, char = 0xd0, solid = true }
"1" = { color = 15, char = 0xd3, solid = true }
"2" = { color = 15, char = 0xd5, solid = true }


[options]
screen_size = [800, 600]

[map]
world= [
"                                ",
" ~~~~~~~     ^^^     ~~   ^^    ",
" ~~~~~~|,   ^^^^     ~~ ^^^||   ",
" ~~~~||| ,   ,^^     ~,^^||     ",
" |||||     ,^^^     ~~  ||      ",
" |||,   ||,   ^^    ~~ ,        ",
"      |||||||^^    ~~     || ^^ ",
" ^     ,||||^^^^|, ~~    |||^^^ ",
"  ^^^|    ,     ,  ==        ^^ ",
"   ^|| ,     |^^   ~~   ,,  ^^^ ",
"  ^^^^|      ^^^^ ~~     , ^^^^ ",
"  ^^^^        ^^^~~          ~  ",
"    ^    ,       ~~         ~~  ",
"             ,  ~~       ||~~~  ",
"     ,      ,  ~~      ,||||~~  ",
"      |        ~~     ,,  |     ",
"   | ,|||T|^  ~~~    ,,      ^^ ",
"  |||   ^^^^ ~~~          ^^^^^ ",
" ^^^||      ~~~~        ^^^^^^^ ",
"  ^^^,     ~~~~      ^^^^^^^^^^ ",
"                                ",
]

